### PR TITLE
Getting all CSS styles more efficiently :)

### PR DESCRIPTION
**Pull request by lukejagodzinski**

### CODE REVIEW

**Review by TejasQ — CHANGES_REQUESTED** [review]
WOW! Thanks for your contribution, @lukejagodzinski!

While this is _amazing_, it breaks the app: it no longer works as a node CLI (`document` doesn’t exist in node). 

Can we detect if we’re in node or in the browser and ship/execute only the relevant code?

**Comment by lukejagodzinski** [comment]
Right, I was expecting that. Sure, I can update that to use jsdom in node. Probably there should be 2 different builds for node and browser. If not today I will update it after New Year's Eve :)

**Comment by TejasQ** [comment]
Awesome! To make sure we ship only the browser JS file to the browser, let’s use dynamic import too! DUDE I LOVE WORKING WITH YOU!

**Comment by lukejagodzinski** [comment]
Closing in favor of https://github.com/TejasQ/get-all-css-properties/pull/3

**Pull request closed without merging**
